title: Chenz 
description: My Personal Blog
author: cz000 
logo: /static/img/avatar.png
github: https://github.com/cz000
about: 闷声发大才

baseurl: ""
url: "http://cz000.github.io/"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 10
per_page: 10
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
