title: Chenz 
description: 闷声发大才
author: cz000 
logo: /static/img/avatar.png
github: https://cz000.github.io/
about: 闷声发大才

baseurl: ""
url: "http://cz000.github.io/"

disqus_shortname: aboutashu
google_analytics: 

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 10
per_page: 10
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
